/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class olympicgames_OlympicGames */

#ifndef _Included_olympicgames_OlympicGames
#define _Included_olympicgames_OlympicGames
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     olympicgames_OlympicGames
 * Method:    numOfParticipants
 * Signature: (Ljava/lang/Long;Ljava/lang/Long;Ljava/lang/String;III)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_olympicgames_OlympicGames_numOfParticipants
  (JNIEnv *, jobject, jobject, jobject, jstring, jint, jint, jint);

/*
 * Class:     olympicgames_OlympicGames
 * Method:    numOfDisciplinesSeason
 * Signature: (Ljava/lang/Long;Ljava/lang/Long;Ljava/lang/String;IIIILjava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_olympicgames_OlympicGames_numOfDisciplinesSeason
  (JNIEnv *, jobject, jobject, jobject, jstring, jint, jint, jint, jint, jstring);

/*
 * Class:     olympicgames_OlympicGames
 * Method:    averageHeightSeason
 * Signature: (Ljava/lang/Long;Ljava/lang/Long;Ljava/lang/String;IIIILjava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_olympicgames_OlympicGames_averageHeightSeason
  (JNIEnv *, jobject, jobject, jobject, jstring, jint, jint, jint, jint, jstring);

/*
 * Class:     olympicgames_OlympicGames
 * Method:    averageWeightSeason
 * Signature: (Ljava/lang/Long;Ljava/lang/Long;Ljava/lang/String;IIIILjava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_olympicgames_OlympicGames_averageWeightSeason
  (JNIEnv *, jobject, jobject, jobject, jstring, jint, jint, jint, jint, jstring);

/*
 * Class:     olympicgames_OlympicGames
 * Method:    initEvents
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_olympicgames_OlympicGames_initEvents
  (JNIEnv *, jclass, jstring);

/*
 * Class:     olympicgames_OlympicGames
 * Method:    initAthletes
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_olympicgames_OlympicGames_initAthletes
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
